# Generated by Django 5.1.7 on 2025-04-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nuotrauka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paveikslelis', models.ImageField(upload_to='nuotraukos/')),
            ],
        ),
    ]
